---
docker_packages:
  - docker

docker_registry_credentials:
  password:  "{{ lookup('env', 'DOCKER_REGISTRY_PASSWORD')}}"
  username: "{{ lookup('env', 'DOCKER_REGISTRY_USER')}}"
  url: "{{ lookup('env', 'DOCKER_REGISTRY') }}"

app_image: "{{ lookup('env', 'DOCKER_REGISTRY_IMAGE') }}:{{ lookup('env', 'DOCKER_IMAGE_TAG') }}"

db_password: "{{ lookup('env', 'DB_PASSWORD') }}"

app_env_vars:
  NODE_ENV: production
  DB_USER: yasmine
  DB_PASSWORD: "{{ db_password }}"
  DB_HOST: users
  DB_NAME: users
app_container_name: express_app_container


postgres_image: postgres:15
postgres_container_name: users
postgres_env_vars:
  POSTGRES_USER: yasmine
  POSTGRES_PASSWORD: "{{ db_password }}"
  POSTGRES_DB: users

postgres_volume_name: pgdata



app_ports:
  - "3000:3000"
postgres_ports:
  - "5432:5432"
docker_network_name: app_net