all:
  hosts:
    ec2_instance:
      ansible_host: "{{ ec2_public_ip }}"
      ansible_user: "{{ ec2_ssh_user }}"
      ansible_ssh_private_key_file: "{{ ec2_priv_ssh_key_path }}"

  vars:
    ec2_instance_id: "{{ ec2_instance_id }}"
